#print env
- name: "print env"
  shell: env

# create uda-backend directory
- name: "create uda-backend directory"
  file:
    path: /home/ubuntu/uda-backend
    state: directory

# un archive artifact.tar.gz to uda-backend directory
- name: "un archive artifact to uda-backend directory"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/uda-backend

# start uda-backend from dist folder
- name: "start uda-backend"
  become: true
  shell: |
    cd /home/ubuntu/uda-backend
    ls -la
    npm install
    pm2 stop default
    pm2 start npm -- start
  register: result

# print output for each task
- name: "print output for each task"
  debug:
    msg: "{{ result.stdout_lines }}"